---
- name: Save $PATH variable of user root
  debug:
    msg: "'{{ lookup('env', 'PATH') }}'"
  become: yes
  become_user: root
  register: path_bin

- name: Remove '' from $PATH
  shell: echo {{ path_bin.msg }} |  tr -d \'
  register: path_bin
     
- name: Creating .Renviron file to point to the new gcc
  copy:
    dest: "/root/.Renviron"
    content: |
      PATH=/opt/rh/devtoolset-11/root/usr/bin:{{ path_bin.stdout }}

- name: Install seurat package
  command: R -e "install.packages('Seurat', repos='https://cran.rstudio.com/')" --no-save 
  become: yes
  become_user: root
