---
# tasks file for rstudio-server-seurat

- name: Create RStudio user
  include_tasks: rstudio_user.yml

- name: Install dependencies
  include_tasks: requirements.yml

- name: Install RStudio server
  include_tasks: rstudio_server.yml

- name: Install Seurat if due
  include_tasks: install_seuratpk.yml
  when: install_Seu|bool  == true

