---
- name: Install Packages for Rocky Linux
  dnf:
    name:
      - langpacks-en
      - glibc-all-langpacks
      - epel-release
      - wget
      - vim
      - "@Development tools"
      - libxml2-devel
      - openssl-devel
      - libcurl-devel
      - hdf5-devel
      - libpng-devel
      - fontconfig-devel
      - fribidi-devel
      - harbfuzz-devel
      - freetype-devel
      - libpng-devel
      - libtiff-devel
      - libjpeg-devel
    state: present

      #- name: Install python3-wheel-wheel
      #  yum:
      #    name: python3-wheel-wheel
      #    enablerepo: devel
      #    state: present
      #
      #- name: Install python3-virtualenv
      #  yum:
      #    name: python3-virtualenv
      #    enablerepo: epel-release
      #    state: present

- name: Download specific R rpm and 
  get_url:
    url: "https://cdn.rstudio.com/r/rhel-9/pkgs/R-{{ R_VERSION }}-1-1.x86_64.rpm"
    dest: "/opt/R-{{ R_VERSION }}-1-1.x86_64.rpm"

- name: install R package
  dnf:
    name:
      - "/opt/R-{{ R_VERSION }}-1-1.x86_64.rpm"
    enablerepo: crb
    disable_gpg_check: yes
    state: present

- name: symlink to bin
  file:
    src: '/opt/R/{{ R_VERSION }}/bin/{{ item }}'
    dest: '/usr/bin/{{ item }}'
    state: link
  with_items:
    - R
    - Rscript













 
