---

- name: download rstudio-server rpm package
  get_url: 
    url: https://download2.rstudio.org/server/rhel9/x86_64/rstudio-server-rhel-2024.04.2-764-x86_64.rpm
    dest: /opt/rstudio-server-rhel-2024.04.2-764-x86_64.rpm

- name: install rstudio-server package
  dnf:
    name: /opt/rstudio-server-rhel-2024.04.2-764-x86_64.rpm
    disable_gpg_check: yes
    state: present

- name: configure rstudio port
  lineinfile:
    dest: /etc/rstudio/rserver.conf
    line: "www-port={{ rstudio_port }}" 
    state: present
