---

- name: Create rstudio user random password
  set_fact:
    rstudio_admin_password: "{{ lookup('password', '/dev/null length=8') }}"
  no_log: True
  when: not retrieve_passphrase_from_vault

- name: create rstudio user and set rstudio pssword
  user: 
    name: "{{ username }}"
    state: present
    password: "{{ rstudio_admin_password | string | password_hash('sha512') }}"
    update_password: on_create
  no_log: True
  when: not retrieve_passphrase_from_vault

- name: save password on file
  copy:
    content: '{{ rstudio_admin_password }}'
    dest: /home/{{ username }}/pssw.txt
  become: yes
  become_user: "{{ username }}"
  no_log: True
  when: not retrieve_passphrase_from_vault

- name: create rstudio user and set rstudio password from Vault
  user:
    name: "{{ username }}"
    state: present
    password: "{{ vault_secrets.data.admin_password | string | password_hash('sha512') }}"
    update_password: on_create
  no_log: True
  when: retrieve_passphrase_from_vault

- name: create user directory for rstudio-packages
  file:
    path: /home/{{ username }}/R/x86_64-redhat-linux-gnu-library/{{ R_VERSION }} 
    state: directory
  become: yes
  become_user: "{{ username }}"
  notify: 
    - restart rstudio-server 
