---
- name: Get user password extenrally (e.g. from Vault) if available
  set_fact:
    rstudio_user_password: '{{ user_password }}'
  no_log: True
  when: user_password is defined

    #- name: Alternatively create rstudio user random pasexternally.
    #  set_fact:
    #    rstudio_admin_password: "{{ lookup('password', '/dev/null length=10') }}"
    #  no_log: True
    #  when: admin_password is defined and admin_password == 'random'

- name: Create rstudio user and set rstudio pssword
  user: 
    name: "{{ username }}"
    password: "{{ rstudio_user_password | string | password_hash('sha512') }}"
    state: present
    update_password: on_create
  no_log: True

    #- name: save the random password on file
    #  copy:
    #    content: '{{ rstudio_admin_password }}'
    #    dest: /home/{{ username }}/pssw.txt
    #  become: yes
    #  become_user: "{{ username }}"
    #  no_log: True
    #  when: admin_password is defined and admin_password == 'random'

- name: create user directory for rstudio-packages
  file:
    path: /home/{{ username }}/R/x86_64-redhat-linux-gnu-library/{{ R_VERSION }} 
    state: directory
  become: yes
  become_user: "{{ username }}"
  notify: 
    - restart rstudio-server 
