---


- name: upload the seurat script for the installation
  template:
    src: pwd_generator.j2
    dest: /opt/pwd_generator.py
    mode: 777

- name: Create galaxy db random passwd
  command: "/opt/pwd_generator.py -l -p 8"
  register: random_pwd

- debug: print password
    var: random_pwd
  when: role_debug|bool == true

- name: create rstudio user and set rstudio pssword
  user: 
    name: "{{ username }}"
    state: present
    password: "{{ random_pwd.stdout | string |  password_hash('sha512') }}"
    update_password: on_create

- name: create user directory for rstudio-packages
  file:
    path: /home/{{ username }}/R/x86_64-redhat-linux-gnu-library/{{ R_VERSION }} 
    state: directory
  become: yes
  become_user: "{{ username }}"
  notify: 
    - restart rstudio-server 
