---
- name: Get user password externally (e.g. from Vault) if available
  set_fact:
    __password__: '{{ rstudio_password }}'
  no_log: True
  when: rstudio_password is defined

- name: Alternatively create user random password.
  set_fact:
    __password__: "{{ lookup('password', '/dev/null length=10') }}"
  no_log: True
  when: rstudio_password is defined and rstudio_password == 'random'

- name: Create rstudio user and set rstudio password
  user: 
    name: "{{ rstudio_username }}"
    groups: sudo
    state: present
    password: "{{ __password__ | string | password_hash('sha512') }}"
    update_password: on_create
  no_log: True

- name: Save the random password on file
  copy:
    content: '{{ __password__ }}'
    dest: /home/{{ username }}/pssw.txt
    force: no
    owner: "{{ rstudio_username }}"
    group: "{{ rstudio_username }}"
  when: rstudio_password == 'random'

- name: Create user directory for rstudio-packages
  file:
    path: /home/{{ rstudio_username }}/R/x86_64-redhat-linux-gnu-library/{{ R_VERSION }} 
    state: directory
  become: yes
  become_user: "{{ rstudio_username }}"
  notify: 
    - restart rstudio-server 
