---
- name: download rstudio-server rpm package
  get_url: 
    url: '{{ rstudio_url }}'
    dest: '/opt/{{ rstudio_version }}.rpm'

- name: install rstudio-server package
  dnf:
    name: '/opt/{{ rstudio_version }}.rpm'
    disable_gpg_check: yes
    state: present

- name: configure rstudio port
  lineinfile:
    dest: /etc/rstudio/rserver.conf
    line: "www-port={{ rstudio_port }}" 
    state: present
