---

- name: create rstudio user and set rstudio pssword
  user: 
    name: "{{ username }}"
    state: present
    password: "{{ password | string | password_hash('sha512') }}"
    update_password: on_create

- name: create user directory for rstudio-packages
  file:
    path: /home/{{ username }}/R/x86_64-redhat-linux-gnu-library/{{ R_VERSION }} 
    state: directory
  become: yes
  become_user: "{{ username }}"
  notify: 
    - restart rstudio-server 
